barbershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

import website.home.urls as home_urls
import website.about.urls as about_urls
import website.online_entry.urls as online_entry_urls
import website.profiles.urls as profiles_urls
import website.services.urls as services_urls
import website.staff.urls as staff_urls
import website.contacts.urls as contacts_urls
import website.sessions.urls as sessions_urls
import website.register.urls as register_urls
import website.login.urls as login_urls


urlpatterns = [
    path('', include((home_urls, 'website.home'), namespace='home')),
    path('online_entry/', include((online_entry_urls, 'website.online_entry'), namespace='online_entry')),
    path('profiles/', include((profiles_urls, 'website.profiles'), namespace='profiles')),
    path('about/', include((about_urls, 'website.about'), namespace='about')),
    path('services/', include((services_urls, 'website.services'), namespace='services')),
    path('staff/', include((staff_urls, 'website.staff'), namespace='staff')),
    path('contacts/', include((contacts_urls, 'website.contacts'), namespace='contacts')),
    path('sessions/', include((sessions_urls, 'website.sessions'), namespace='sessions')),
    path('register/', include((register_urls, 'website.register'), namespace='register')),
    path('login/', include((login_urls, 'website.login'), namespace='login')),
    path('logout/', LogoutView.as_view(template_name='home/index.html'), name='logout'),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/home/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/index.html'), name='index')
]

website/profiles/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ProfileDetailView

urlpatterns = [
    path('profile/details/', login_required(ProfileDetailView.as_view()), name='profile_details')
]

templates/base/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Barbershop - {% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">

</head>


<body>
{% include 'base/navbar.html' %}
{% block content %}{% endblock %}

<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
<!-- Instantiate single textfield component rendered in the document -->
<script>
    mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-text-field'));
</script>

</body>
</html>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div>
        <a class="navbar-brand" href="{% url 'home:index' %}">Barbershop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'about:index' %}">О нас<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'services:index' %}">Услуги<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'staff:index' %}">Команда<span
                            class="sr-only">(current)</span></a>
                </li>
                {#                <li class="nav-item active">#}
                {#                    <a class="nav-link" href="{% url 'website:contact_main' %}">Контакты<span#}
                {#                            class="sr-only">(current)</span></a>#}
                {#                </li>#}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'profiles:profile_details' %}">Личные данные<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'sessions:index' %}">Мои записи<span
                            class="sr-only">(current)</span></a>
                </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'logout' %}">Выйти<span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'about:index' %}">О нас<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'services:index' %}">Услуги<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'staff:index' %}">Команда<span
                            class="sr-only">(current)</span></a>
                </li>
                {#                <li class="nav-item active">#}
                {#                    <a class="nav-link" href="{% url 'contacts:index' %}">Контакты<span#}
                {#                            class="sr-only">(current)</span></a>#}
                {#                </li>#}
            {% endif %}
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if not request.user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login:index' %}">Войти<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'register:index' %}">Зарегистрироваться<span
                            class="sr-only">(current)</span></a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>