barbershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

import website.home.urls as home_urls
import website.about.urls as about_urls
import website.online_entry.urls as online_entry_urls
import website.profiles.urls as profiles_urls
import website.services.urls as services_urls
import website.staff.urls as staff_urls
import website.contacts.urls as contacts_urls
import website.sessions.urls as sessions_urls
import website.register.urls as register_urls
import website.login.urls as login_urls


urlpatterns = [
    path('', include((home_urls, 'website.home'), namespace='home')),
    path('online_entry/', include((online_entry_urls, 'website.online_entry'), namespace='online_entry')),
    path('profiles/', include((profiles_urls, 'website.profiles'), namespace='profiles')),
    path('about/', include((about_urls, 'website.about'), namespace='about')),
    path('services/', include((services_urls, 'website.services'), namespace='services')),
    path('staff/', include((staff_urls, 'website.staff'), namespace='staff')),
    path('contacts/', include((contacts_urls, 'website.contacts'), namespace='contacts')),
    path('sessions/', include((sessions_urls, 'website.sessions'), namespace='sessions')),
    path('register/', include((register_urls, 'website.register'), namespace='register')),
    path('login/', include((login_urls, 'website.login'), namespace='login')),
    path('logout/', LogoutView.as_view(template_name='home/index.html'), name='logout'),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/online_entry/urls.py
from django.urls import path
from .views import ServicesFormView, StaffFormView
from django.views.generic import TemplateView

urlpatterns = [
    path('choose_service/', ServicesFormView.as_view(), name='choose_service'),
    path('choose_staff/', StaffFormView.as_view(template_name='online_entry/choose_staff.html'), name='choose_staff'),
    # path('choose_date/', TemplateView.as_view(template_name='online_entry/choose_date.html'), name='choose_date')
]

website/services/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='services/index.html'), name='index')
]

templates/services/index.html
{% extends 'base/layout.html' %}
{% block title %}Services{% endblock %}
{% load static %}

{% block content %}
    <section class="section section--prices" id="prices">
        <header class="section__header">
            <h2>Мы умеем</h2>
        </header>

        <div class="section__content section__content--prices">
            <div class="prices-wrapper">
                <div class="price-inner__column">
                    <table class="prices-table">
                        <caption>Основные услуги</caption>
                        <tbody>
                        <tr>
                            <td>Стрижка мужская</td>
                            <td>45 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">подбор стрижки, 2 мытья, укладка</td>
                        </tr>
                        <tr>
                        </tr>
                        <tr>
                            <td>Стрижка удлиненная</td>
                            <td>65 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">подбор стрижки, 2 мытья, укладка</td>
                        </tr>
                        <tr>
                        </tr>
                        <tr>
                            <td>Стрижка машинкой</td>
                            <td>30 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">без ножниц</td>
                        </tr>
                        <tr>
                        </tr>
                        <tr>
                            <td>Стрижка детская</td>
                            <td>35 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">от 4 до 14 лет включительно, не удлиненная</td>
                        </tr>
                        <tr>
                        </tr>
                        <tr>
                        </tr>
                        <tr>
                            <td>Стрижка бороды</td>
                            <td>30 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">с распариванием и окантовкой бритвой шаветт</td>
                        </tr>
                        <tr>
                        </tr>
                        <tr>
                            <td>Классическое бритьё</td>
                            <td>45 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td>Королевское бритьё</td>
                            <td>60 <span>p.</span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <div class="price-inner__column price-inner__column--right">
                    <table class="prices-table">
                        <caption>Комплексные услуги</caption>
                        <tbody>
                        <tr>
                            <td>Отец + сын</td>
                            <td>70 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td>Друг + друг</td>
                            <td>80 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td>Стрижка + Бритьё</td>
                            <td>80 <span>p.</span></td>
                        </tr>
                        </tbody>
                    </table>

                    <table class="prices-table">
                        <caption>Дополнительные услуги</caption>
                        <tbody>
                        <tr>
                            <td>Укладка волос</td>
                            <td>10 <span>p.</span></td>
                        </tr>

                        <tr>
                            <td>Коррекция воском</td>
                            <td>15 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">удаление нежелательных волос на лице</td>
                        </tr>

                        <tr>
                            <td>Камуфляж седины</td>
                            <td>35 <span>p.</span></td>
                        </tr>
                        <tr>
                            <td class="prices-table__desc" colspan="2">предварительная консультация с мастером</td>
                        </tr>

                        <tr>
                            <td>Бритьё головы</td>
                            <td>40 <span>p.</span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <div class="price-logo">
                    <div class="price-logo__image">
                        <img height="150" width="150" src="{% static 'img/logo.png' %}"
                             alt="Trueman Barberhop Logo">
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                    <a class="button ms_booking" href="{% url 'online_entry:choose_service' %}">Запись онлайн</a>
                {% else %}
                    <a class="button ms_booking" href="{% url 'website.login:index' %}">Запись онлайн</a>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}